module.exports = [

  // ═══════════════════════════════════════════════════════
  // الأصول (1000) - ASSETS
  // ═══════════════════════════════════════════════════════
  {
    code: "1",
    name: "الأصول",
    type: "asset",
    category: "assets",
    level: 1,
    parentCode: null,
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },

  // ── أصول غير متداولة (1100) ──
  {
    code: "11",
    name: "أصول غير متداولة",
    type: "asset",
    category: "fixed_assets",
    level: 2,
    parentCode: "1",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  // 1102 - أصول ثابتة
  {
    code: "1102",
    name: "أصول ثابتة",
    type: "asset",
    category: "fixed_assets",
    level: 3,
    parentCode: "11",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  {
    code: "110200",
    name: "أراضي",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1102",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110201",
    name: "مباني",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1102",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110202",
    name: "سيارات",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1102",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110203",
    name: "أثاث وتجهيزات",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1102",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110204",
    name: "حاسب آلي وطابعات",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1102",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110205",
    name: "تحسينات على المأجور",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1102",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110206",
    name: "آلات ومعدات",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1102",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110207",
    name: "مجمع إهلاك الأصول الثابتة",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1102",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  // 1103 - مشروعات تحت التنفيذ
  {
    code: "1103",
    name: "مشروعات تحت التنفيذ",
    type: "asset",
    category: "fixed_assets",
    level: 3,
    parentCode: "11",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  {
    code: "110300",
    name: "مشروعات تحت التنفيذ - أراضي",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1103",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110301",
    name: "مشروعات تحت التنفيذ - مباني",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1103",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110302",
    name: "مشروعات تحت التنفيذ - معدات",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1103",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  // 1104 - استثمارات طويلة الأجل
  {
    code: "1104",
    name: "استثمارات طويلة الأجل",
    type: "asset",
    category: "fixed_assets",
    level: 3,
    parentCode: "11",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  {
    code: "110400",
    name: "استثمارات في شركات تابعة",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1104",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110401",
    name: "استثمارات في شركات زميلة",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1104",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110402",
    name: "ودائع طويلة الأجل",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1104",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  // 1105 - أصول غير ملموسة
  {
    code: "1105",
    name: "أصول غير ملموسة",
    type: "asset",
    category: "fixed_assets",
    level: 3,
    parentCode: "11",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  {
    code: "110500",
    name: "براءات اختراع",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1105",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110501",
    name: "علامات تجارية",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1105",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110502",
    name: "حقوق امتياز",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1105",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110503",
    name: "برامج حاسب آلي",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1105",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },
  {
    code: "110504",
    name: "مجمع إطفاء الأصول غير الملموسة",
    type: "asset",
    category: "fixed_assets",
    level: 4,
    parentCode: "1105",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "investing"
  },

  // ── أصول متداولة (1200) ──
  {
    code: "12",
    name: "أصول متداولة",
    type: "asset",
    category: "current_assets",
    level: 2,
    parentCode: "1",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  // 1201 - النقدية بالصندوق
  {
    code: "1201",
    name: "النقدية بالصندوق",
    type: "asset",
    category: "cash",
    level: 3,
    parentCode: "12",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },

  // 1202 - النقدية بالبنك
  {
    code: "1202",
    name: "النقدية بالبنك",
    type: "asset",
    category: "cash",
    level: 3,
    parentCode: "12",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  // 1203 - العملاء
  {
    code: "1203",
    name: "العملاء",
    type: "asset",
    category: "receivables",
    level: 3,
    parentCode: "12",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },

  // 1204 - المناديب
  {
    code: "1204",
    name: "المناديب",
    type: "asset",
    category: "receivables",
    level: 3,
    parentCode: "12",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  // 1205 - المخزون
  {
    code: "1205",
    name: "المخزون",
    type: "asset",
    category: "current_assets",
    level: 3,
    parentCode: "12",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  {
    code: "120500",
    name: "مخزون بضاعة أول المدة",
    type: "asset",
    category: "current_assets",
    level: 4,
    parentCode: "1205",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "120501",
    name: "تكلفة المخزون",
    type: "asset",
    category: "current_assets",
    level: 4,
    parentCode: "1205",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "120502",
    name: "مخزون آخر المدة",
    type: "asset",
    category: "current_assets",
    level: 4,
    parentCode: "1205",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "120503",
    name: "بضاعة في الطريق",
    type: "asset",
    category: "current_assets",
    level: 4,
    parentCode: "1205",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit"
  },
  {
    code: "120504",
    name: "بضاعة على التجربة",
    type: "asset",
    category: "current_assets",
    level: 4,
    parentCode: "1205",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit"
  },
  {
    code: "120505",
    name: "مخصص بضاعة راكدة",
    type: "asset",
    category: "current_assets",
    level: 4,
    parentCode: "1205",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "none",
    cfsection: "operating"
  },
  // 1206 - أوراق قبض
  {
    code: "1206",
    name: "أوراق قبض",
    type: "asset",
    category: "receivables",
    level: 3,
    parentCode: "12",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  {
    code: "120600",
    name: "أوراق قبض محلية",
    type: "asset",
    category: "receivables",
    level: 4,
    parentCode: "1206",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit"
  },
  {
    code: "120601",
    name: "أوراق قبض دولية",
    type: "asset",
    category: "receivables",
    level: 4,
    parentCode: "1206",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit"
  },
  {
    code: "120602",
    name: "أوراق قبض تحت التحصيل",
    type: "asset",
    category: "receivables",
    level: 4,
    parentCode: "1206",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit"
  },
  {
    code: "120603",
    name: "أوراق قبض مخصومة",
    type: "asset",
    category: "receivables",
    level: 4,
    parentCode: "1206",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit"
  },
  // 1207 - استثمارات قصيرة الأجل
  {
    code: "1207",
    name: "استثمارات قصيرة الأجل",
    type: "asset",
    category: "current_assets",
    level: 3,
    parentCode: "12",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  {
    code: "120700",
    name: "أسهم للتداول",
    type: "asset",
    category: "current_assets",
    level: 4,
    parentCode: "1207",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit"
  },
  {
    code: "120701",
    name: "سندات للتداول",
    type: "asset",
    category: "current_assets",
    level: 4,
    parentCode: "1207",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit"
  },
  {
    code: "120702",
    name: "صناديق استثمار",
    type: "asset",
    category: "current_assets",
    level: 4,
    parentCode: "1207",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit"
  },
  // 1208 - مصاريف مدفوعة مقدماً
  {
    code: "1208",
    name: "مصاريف مدفوعة مقدماً",
    type: "asset",
    category: "prepaid",
    level: 3,
    parentCode: "12",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  {
    code: "120800",
    name: "إيجارات مدفوعة مقدماً",
    type: "asset",
    category: "prepaid",
    level: 4,
    parentCode: "1208",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "120801",
    name: "تأمينات مدفوعة مقدماً",
    type: "asset",
    category: "prepaid",
    level: 4,
    parentCode: "1208",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "120802",
    name: "اشتراكات مدفوعة مقدماً",
    type: "asset",
    category: "prepaid",
    level: 4,
    parentCode: "1208",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "120803",
    name: "رسوم بنكية مدفوعة مقدماً",
    type: "asset",
    category: "prepaid",
    level: 4,
    parentCode: "1208",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "none",
    cfsection: "none"
  },
  {
    code: "120804",
    name: "مصاريف تسويق مدفوعة مقدماً",
    type: "asset",
    category: "prepaid",
    level: 4,
    parentCode: "1208",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  // 1209 - مدينون متنوعون
  {
    code: "1209",
    name: "مدينون متنوعون وأرصدة مدينة أخرى",
    type: "asset",
    category: "receivables",
    level: 3,
    parentCode: "12",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  {
    code: "120900",
    name: "ضريبة القيمة المضافة للمدخلات",
    type: "asset",
    category: "current_assets",
    level: 4,
    parentCode: "1209",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "120901",
    name: "عملاء مشكوك في تحصيلهم",
    type: "asset",
    category: "receivables",
    level: 4,
    parentCode: "1209",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "inflow",
    cfsection: "operating"
  },
  {
    code: "120902",
    name: "سلف الموظفين",
    type: "asset",
    category: "current_assets",
    level: 4,
    parentCode: "1209",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "120903",
    name: "دفعات مقدمة للموردين",
    type: "asset",
    category: "prepaid",
    level: 4,
    parentCode: "1209",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "120904",
    name: "خطابات ضمان بنكية",
    type: "asset",
    category: "bank",
    level: 4,
    parentCode: "1209",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "none",
    cfsection: "none"
  },
  {
    code: "120905",
    name: "عمولات مدفوعة مقدماً",
    type: "asset",
    category: "prepaid",
    level: 4,
    parentCode: "1209",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "120906",
    name: "مطالبات تأمين",
    type: "asset",
    category: "receivables",
    level: 4,
    parentCode: "1209",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit"
  },
  {
    code: "120907",
    name: "إيرادات مستحقة",
    type: "asset",
    category: "receivables",
    level: 4,
    parentCode: "1209",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "inflow",
    cfsection: "operating"
  },
  {
    code: "120908",
    name: "ضريبة دخل مدفوعة مقدماً",
    type: "asset",
    category: "current_assets",
    level: 4,
    parentCode: "1209",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "120909",
    name: "زكاة مدفوعة مقدماً",
    type: "asset",
    category: "current_assets",
    level: 4,
    parentCode: "1209",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },

  // ═══════════════════════════════════════════════════════
  // الإلتزامات وحقوق الملكية (2000) - LIABILITIES & EQUITY
  // ═══════════════════════════════════════════════════════
  {
    code: "2",
    name: "الإلتزامات وحقوق الملكية",
    type: "liability",
    category: "liabilities",
    level: 1,
    parentCode: null,
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },

  // ── حقوق الملكية (2100) ──
  {
    code: "21",
    name: "حقوق الملكية",
    type: "equity",
    category: "equity",
    level: 2,
    parentCode: "2",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "2101",
    name: "حقوق الملكية",
    type: "equity",
    category: "equity",
    level: 3,
    parentCode: "21",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "210100",
    name: "رأس المال",
    type: "equity",
    category: "equity",
    level: 4,
    parentCode: "2101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "inflow",
    cfsection: "financing"
  },
  {
    code: "210101",
    name: "إحتياطي نظامي",
    type: "equity",
    category: "equity",
    level: 4,
    parentCode: "2101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "financing"
  },
  {
    code: "210102",
    name: "إحتياطي عام",
    type: "equity",
    category: "equity",
    level: 4,
    parentCode: "2101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "financing"
  },
  {
    code: "210103",
    name: "إحتياطي مخصص",
    type: "equity",
    category: "equity",
    level: 4,
    parentCode: "2101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "financing"
  },
  {
    code: "210104",
    name: "أرباح سنوات سابقة",
    type: "equity",
    category: "equity",
    level: 4,
    parentCode: "2101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "outflow",
    cfsection: "financing"
  },
  {
    code: "210105",
    name: "أرباح وخسائر العام",
    type: "equity",
    category: "equity",
    level: 4,
    parentCode: "2101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "financing"
  },
  {
    code: "210106",
    name: "رأس مال أرصدة أول المدة",
    type: "equity",
    category: "equity",
    level: 4,
    parentCode: "2101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "financing"
  },
  {
    code: "210107",
    name: "خسائر متراكمة",
    type: "equity",
    category: "equity",
    level: 4,
    parentCode: "2101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "financing"
  },
  // 2102 - أسهم الخزينة
  {
    code: "2102",
    name: "أسهم الخزينة",
    type: "equity",
    category: "equity",
    level: 3,
    parentCode: "21",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "210200",
    name: "أسهم خزينة - تكلفة",
    type: "equity",
    category: "equity",
    level: 4,
    parentCode: "2102",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "financing"
  },
  // 2103 - فروق إعادة تقييم
  {
    code: "2103",
    name: "فروق إعادة تقييم",
    type: "equity",
    category: "equity",
    level: 3,
    parentCode: "21",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "210300",
    name: "فروق إعادة تقييم الأصول الثابتة",
    type: "equity",
    category: "equity",
    level: 4,
    parentCode: "2103",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "financing"
  },
  {
    code: "210301",
    name: "فروق إعادة تقييم الاستثمارات",
    type: "equity",
    category: "equity",
    level: 4,
    parentCode: "2103",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "financing"
  },

  // ── إلتزامات غير متداولة (2200) ──
  {
    code: "22",
    name: "إلتزامات غير متداولة",
    type: "liability",
    category: "non_current_liabilities",
    level: 2,
    parentCode: "2",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "2201",
    name: "المخصصات",
    type: "liability",
    category: "non_current_liabilities",
    level: 3,
    parentCode: "22",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "220100",
    name: "مخصص إهلاك أصول ثابتة",
    type: "liability",
    category: "non_current_liabilities",
    level: 4,
    parentCode: "2201",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "operating"
  },
  {
    code: "220101",
    name: "مخصص ديون مشكوك في تحصيلها",
    type: "liability",
    category: "non_current_liabilities",
    level: 4,
    parentCode: "2201",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "operating"
  },
  {
    code: "220102",
    name: "مخصص بضاعة راكدة",
    type: "liability",
    category: "non_current_liabilities",
    level: 4,
    parentCode: "2201",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "operating"
  },
  {
    code: "220103",
    name: "مخصص مكافأة ترك الخدمة",
    type: "liability",
    category: "non_current_liabilities",
    level: 4,
    parentCode: "2201",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "operating"
  },
  {
    code: "220104",
    name: "مخصص ضريبة دخل مؤجل",
    type: "liability",
    category: "non_current_liabilities",
    level: 4,
    parentCode: "2201",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "operating"
  },
  {
    code: "220105",
    name: "مخصص زكاة مؤجل",
    type: "liability",
    category: "non_current_liabilities",
    level: 4,
    parentCode: "2201",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "operating"
  },
  {
    code: "2202",
    name: "قروض طويلة الأجل",
    type: "liability",
    category: "non_current_liabilities",
    level: 3,
    parentCode: "22",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "220200",
    name: "قروض بنكية طويلة الأجل",
    type: "liability",
    category: "non_current_liabilities",
    level: 4,
    parentCode: "2202",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "none"
  },
  {
    code: "220201",
    name: "سندات إصدار",
    type: "liability",
    category: "non_current_liabilities",
    level: 4,
    parentCode: "2202",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  {
    code: "220202",
    name: "قروض من مؤسسات تمويل",
    type: "liability",
    category: "non_current_liabilities",
    level: 4,
    parentCode: "2202",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  {
    code: "220203",
    name: "قروض من أطراف ذات علاقة طويلة",
    type: "liability",
    category: "non_current_liabilities",
    level: 4,
    parentCode: "2202",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "outflow",
    cfsection: "operating"
  },
  // 2203 - إلتزامات تأجير تمويلي
  {
    code: "2203",
    name: "إلتزامات تأجير تمويلي",
    type: "liability",
    category: "non_current_liabilities",
    level: 3,
    parentCode: "22",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "220300",
    name: "إلتزامات تأجير تمويلي - سيارات",
    type: "liability",
    category: "non_current_liabilities",
    level: 4,
    parentCode: "2203",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  {
    code: "220301",
    name: "إلتزامات تأجير تمويلي - معدات",
    type: "liability",
    category: "non_current_liabilities",
    level: 4,
    parentCode: "2203",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  // 2204 - إلتزامات مؤجلة
  {
    code: "2204",
    name: "إلتزامات مؤجلة",
    type: "liability",
    category: "non_current_liabilities",
    level: 3,
    parentCode: "22",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "220400",
    name: "إيرادات مؤجلة طويلة الأجل",
    type: "liability",
    category: "non_current_liabilities",
    level: 4,
    parentCode: "2204",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "inflow",
    cfsection: "operating"
  },
  {
    code: "220401",
    name: "منح حكومية مؤجلة",
    type: "liability",
    category: "non_current_liabilities",
    level: 4,
    parentCode: "2204",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },

  // ── إلتزامات متداولة (2300) ──
  {
    code: "23",
    name: "إلتزامات متداولة",
    type: "liability",
    category: "current_liabilities",
    level: 2,
    parentCode: "2",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "2301",
    name: "الموردين",
    type: "liability",
    category: "current_liabilities",
    level: 3,
    parentCode: "23",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "2302",
    name: "قروض قصيرة الأجل",
    type: "liability",
    category: "current_liabilities",
    level: 3,
    parentCode: "23",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "230200",
    name: "قروض بنكية قصيرة الأجل",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2302",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "none"
  },
  {
    code: "230201",
    name: "تسهيلات بنكية",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2302",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "none"
  },
  {
    code: "230202",
    name: "كشوف حساب جارية مدينة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2302",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  {
    code: "230203",
    name: "قروض من أطراف ذات علاقة قصيرة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2302",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "2303",
    name: "مصاريف مستحقة وأرصدة دائنة أخرى",
    type: "liability",
    category: "current_liabilities",
    level: 3,
    parentCode: "23",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "230300",
    name: "رواتب مستحقة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2303",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "230301",
    name: "إجازات مستحقة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2303",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  {
    code: "230302",
    name: "تذاكر مستحقة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2303",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "230303",
    name: "إيجارات مستحقة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2303",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  {
    code: "230304",
    name: "دفعات مقدمة من العملاء",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2303",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "inflow",
    cfsection: "operating"
  },
  {
    code: "230305",
    name: "ضريبة القيمة المضافة للمخرجات",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2303",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "230306",
    name: "مصلحة الزكاة والضريبة - ضريبة قيمة مضافة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2303",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "230307",
    name: "مصلحة الزكاة والضريبة - الزكاة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2303",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "230308",
    name: "مصلحة الزكاة والضريبة - ضريبة دخل",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2303",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "230309",
    name: "تأمينات اجتماعية مستحقة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2303",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  {
    code: "230310",
    name: "عمولات مستحقة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2303",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  {
    code: "230311",
    name: "مصاريف بنكية مستحقة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2303",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "none",
    cfsection: "none"
  },
  {
    code: "230312",
    name: "أرباح مستحقة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2303",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  {
    code: "2304",
    name: "المستحق إلى أطراف ذات علاقة",
    type: "liability",
    category: "current_liabilities",
    level: 3,
    parentCode: "23",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "230400",
    name: "المستحق إلى الشريك - شريك 1",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2304",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "230401",
    name: "المستحق إلى الشريك - شريك 2",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2304",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "230402",
    name: "المستحق إلى الشريك - شريك 3",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2304",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "230403",
    name: "المستحق إلى الشركة الأم",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2304",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  {
    code: "230404",
    name: "المستحق إلى الشركات التابعة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2304",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  // 2305 - أوراق دفع
  {
    code: "2305",
    name: "أوراق دفع",
    type: "liability",
    category: "current_liabilities",
    level: 3,
    parentCode: "23",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "230500",
    name: "أوراق د_payable محلية",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2305",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  {
    code: "230501",
    name: "أوراق د_payable دولية",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2305",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  {
    code: "230502",
    name: "أوراق د_payable تحت التسوية",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2305",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  // 2306 - إلتزامات تأجير تمويلي قصيرة
  {
    code: "2306",
    name: "إلتزامات تأجير تمويلي - قصيرة",
    type: "liability",
    category: "current_liabilities",
    level: 3,
    parentCode: "23",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "230600",
    name: "إلتزامات تأجير تمويلي قصيرة - سيارات",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2306",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  {
    code: "230601",
    name: "إلتزامات تأجير تمويلي قصيرة - معدات",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2306",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },
  // 2307 - إيرادات مؤجلة
  {
    code: "2307",
    name: "إيرادات مؤجلة",
    type: "liability",
    category: "current_liabilities",
    level: 3,
    parentCode: "23",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "230700",
    name: "إيرادات اشتراكات مؤجلة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2307",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "inflow",
    cfsection: "operating"
  },
  {
    code: "230701",
    name: "إيرادات صيانة مؤجلة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2307",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "inflow",
    cfsection: "operating"
  },
  {
    code: "230702",
    name: "منح حكومية مؤجلة - قصيرة",
    type: "liability",
    category: "current_liabilities",
    level: 4,
    parentCode: "2307",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit"
  },

  // ═══════════════════════════════════════════════════════
  // الإيرادات (3000) - REVENUE
  // ═══════════════════════════════════════════════════════
  {
    code: "3",
    name: "الإيرادات",
    type: "revenue",
    category: "revenue",
    level: 1,
    parentCode: null,
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },

  // ── إيرادات النشاط (3100) ──
  {
    code: "31",
    name: "إيرادات النشاط",
    type: "revenue",
    category: "sales_revenue",
    level: 2,
    parentCode: "3",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "3101",
    name: "ايرادات مبيعات",
    type: "revenue",
    category: "sales_revenue",
    level: 3,
    parentCode: "31",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  {
    code: "310100",
    name: "المبيعات",
    type: "revenue",
    category: "sales_revenue",
    level: 4,
    parentCode: "3101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "inflow",
    cfsection: "operating"
  },
  {
    code: "310101",
    name: "مردودات المبيعات",
    type: "revenue",
    category: "sales_revenue",
    level: 4,
    parentCode: "3101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "inflow",
    cfsection: "operating"
  },
  {
    code: "310102",
    name: "خصومات المبيعات",
    type: "revenue",
    category: "sales_revenue",
    level: 4,
    parentCode: "3101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "credit",
    cftype: "inflow",
    cfsection: "operating"
  },
  // ── إيرادات عامة (3200) ──
  {
    code: "32",
    name: "إيرادات عامة",
    type: "revenue",
    category: "other_revenue",
    level: 2,
    parentCode: "3",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "credit"
  },
  // ═══════════════════════════════════════════════════════
  // المصروفات (4000) - EXPENSES
  // ═══════════════════════════════════════════════════════
  {
    code: "4",
    name: "المصروفات",
    type: "expense",
    category: "expenses",
    level: 1,
    parentCode: null,
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },

  // ── تكلفة الإيرادات (4100) ──
  {
    code: "41",
    name: "تكلفة الإيرادات",
    type: "expense",
    category: "cost_of_sales",
    level: 2,
    parentCode: "4",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  {
    code: "4101",
    name: "تكلفة البضاعة المباعة",
    type: "expense",
    category: "cost_of_sales",
    level: 3,
    parentCode: "41",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  {
    code: "410100",
    name: "المشتريات",
    type: "expense",
    category: "cost_of_sales",
    level: 4,
    parentCode: "4101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "410101",
    name: "تغير في المخزون",
    type: "expense",
    category: "cost_of_sales",
    level: 4,
    parentCode: "4101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "410102",
    name: "مصاريف الشحن على المشتريات",
    type: "expense",
    category: "cost_of_sales",
    level: 4,
    parentCode: "4101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "410103",
    name: "رسوم جمركية",
    type: "expense",
    category: "cost_of_sales",
    level: 4,
    parentCode: "4101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "410104",
    name: "تأمين على الشحنات",
    type: "expense",
    category: "cost_of_sales",
    level: 4,
    parentCode: "4101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "410105",
    name: "مردودات المشتريات",
    type: "expense",
    category: "cost_of_sales",
    level: 4,
    parentCode: "4101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  {
    code: "410106",
    name: "خصومات المشتريات",
    type: "expense",
    category: "cost_of_sales",
    level: 4,
    parentCode: "4101",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "outflow",
    cfsection: "operating"
  },
  // ── إهلاك الأصول الثابتة (4200) ──
  {
    code: "42",
    name: "إهلاك الأصول الثابتة",
    type: "expense",
    category: "depreciation_expense",
    level: 2,
    parentCode: "4",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  {
    code: "4201",
    name: "مصروفات الإهلاك",
    type: "expense",
    category: "depreciation_expense",
    level: 3,
    parentCode: "42",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  {
    code: "420100",
    name: "مصروف إهلاك الأصول الثابتة",
    type: "expense",
    category: "depreciation_expense",
    level: 4,
    parentCode: "4201",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "none",
    cfsection: "operating"
  },
  // 4202 - خسارة بيع أصول
  {
    code: "4202",
    name: "خسائر بيع الأصول",
    type: "expense",
    category: "depreciation_expense",
    level: 3,
    parentCode: "42",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
  {
    code: "420200",
    name: "خسارة بيع أصول ثابتة",
    type: "expense",
    category: "depreciation_expense",
    level: 4,
    parentCode: "4202",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "none",
    cfsection: "operating"
  },
  {
    code: "420201",
    name: "خسارة بيع استثمارات",
    type: "expense",
    category: "depreciation_expense",
    level: 4,
    parentCode: "4202",
    isLeaf: true,
    allowTransactions: true,
    normalBalance: "debit",
    cftype: "none",
    cfsection: "operating"
  },

  // ── المصاريف العامة والإدارية (4300) ──
  {
    code: "43",
    name: "المصاريف العامة والإدارية",
    type: "expense",
    category: "operating_expenses",
    level: 2,
    parentCode: "4",
    isLeaf: false,
    allowTransactions: false,
    normalBalance: "debit"
  },
];